server: 
  port: 5005
  error: 
    include-binding-errors: always
    include-message: always
    include-exception: true

spring:
  application:
    name: payment-service
  datasource:
    hikari:
      autoCommit: false
    url: jdbc:postgresql://localhost:5433/paymentService?createDatabaseIfNotExist=true
    username: postgres
    password: aylaadem233
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

gocardless:
  api:
    key: YOUR_GOCARDLESS_API_KEY
    secret: YOUR_GOCARDLESS_API_SECRET

stripe:
  api:
    key: YOUR_STRIPE_API_KEY
    secret: YOUR_STRIPE_API_SECRET

info:
  application: 
    name: 'category service' 
    description: 'This is a Payment microservice for saloon booking system'
    version: '@project.version@' 
